/* confdefs.h */
#define PACKAGE_NAME "cashwebtools"
#define PACKAGE_TARNAME "cashwebtools"
#define PACKAGE_VERSION "0"
#define PACKAGE_STRING "cashwebtools 0"
#define PACKAGE_BUGREPORT ""
#define PACKAGE_URL ""
#define PACKAGE "cashwebtools"
#define VERSION "0"
#define STDC_HEADERS 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_MEMORY_H 1
#define HAVE_STRINGS_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_STDINT_H 1
#define HAVE_UNISTD_H 1
#define HAVE_DLFCN_H 1
#define LT_OBJDIR ".libs/"
#define HAVE_LIBDL 1
#define HAVE_DLERROR 1
#define HAVE_LIBDLLOADER 1
#define DATADIR "/usr/local/share"
#define HAVE_ARPA_INET_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STDINT_H 1
#define HAVE_STRING_H 1
#define HAVE_UNISTD_H 1
#define HAVE__BOOL 1
#define HAVE_STDLIB_H 1
#define HAVE_MALLOC 1
#define HAVE_STDLIB_H 1
#define HAVE_REALLOC 1
#define HAVE_BZERO 1
#define HAVE_INET_NTOA 1
#define HAVE_MEMSET 1
#define HAVE_STRDUP 1
#define HAVE_STRRCHR 1
#define HAVE_STRSTR 1
#define HAVE_STRTOUL 1
